# Generated by Django 4.0.1 on 2022-05-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentregister',
            table='add_student',
        ),
    ]
